#!/usr/bin/env bash

Rscript -e 'install.packages("car", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("MuMIn", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("lme4", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("vegan", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("tidyverse", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("viridis", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("ggplot2", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("fields", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("ecodist", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("brms", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("picante", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("bipartite", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("bayesplot", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("tidybayes", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("performance", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("gridExtra", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("tidytree", repos="http://cran.r-project.org")'
Rscript -e 'install.packages("lemon", repos="http://cran.r-project.org")'
